### ISSUE TITLE
[BUG] [<EnvTransform>]: Task unable to process fields where value is empty

### ISSUE THREAD

**Issue by m-thomsen** [joachimdalen/AzureDevOpsExtensions#3] opened 2021-01-22 20:26 UTC
**Describe the bug**
Getting the following error message:
##[error]Cannot read property 'trim' of undefined

This appears to be happen if you have values which are blank, eg:
LOG_CHANNEL=
LOG_LEVEL=debug

LOG_CHANNEL would be the cause of the issue. The desired behavior is the task continues and either fill in a value, or skip this particular key

**Agent Type**
- [ ] Hosted
- [x] Self Hosted

**Agent OS**
- [ ] Windows
- [x] Linux
- [ ] OSX

**Logs**

Raw build log:
```
2021-01-22T20:00:26.4282220Z ##[section]Starting: Apply Env config
2021-01-22T20:00:26.4295190Z ==============================================================================
2021-01-22T20:00:26.4295827Z Task         : EnvTransform
2021-01-22T20:00:26.4296508Z Description  : A task to perform variable replacement for environment files
2021-01-22T20:00:26.4297078Z Version      : 0.2.1
2021-01-22T20:00:26.4297524Z Author       : Joachim Dalen
2021-01-22T20:00:26.4298319Z Help         : [Learn more about this task](https://marketplace.visualstudio.com/items?itemName=joachimdalen.env-transform)
2021-01-22T20:00:26.4299242Z ==============================================================================
2021-01-22T20:00:26.5652205Z ##[error]Cannot read property 'trim' of undefined
2021-01-22T20:00:26.5688670Z ##[section]Finishing: Apply Env config
```

**Comment by joachimdalen** [comment] 2021-01-23 08:57
Hi!

Thank you for reporting the issue. This should now be fixed in:

Extension version: `1.2.0`
Task version: `0.3.0`

Can you verify that this works as intended in your pipeline now?

**Comment by joachimdalen** [comment] 2021-01-28 16:47
Due to the lack of response I will close this issue. Please reopen it if you still have issues.

**Closed by joachimdalen** 2021-01-28 16:47 UTC
Labels: bug
